services:
  - type: web
    name: erpguard-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run erpguard/dashboard/app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api-db

  - type: worker
    name: erpguard-compliance-runner
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python erpguard/validation/rules_engine.py && python erpguard/compliance_summary.py && python erpguard/reporting/generate_report.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api-db
