services:
  - type: web
    name: erpguard-dashboard
    env: python
    plan: free
    buildCommand: |
  echo "SHOWING FILES IN ROOT:"
  ls -la
  echo "SHOWING CONTENTS OF runtime.txt"
  cat runtime.txt || echo "NO runtime.txt found"
  pip install --upgrade pip
  pip install poetry
  poetry install
    startCommand: "poetry run streamlit run erpguard/dashboard/app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api-db
          property: connectionString

  - type: worker
    name: erpguard-compliance-runner
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install poetry
      poetry install
    startCommand: >
      poetry run python erpguard/validation/rules_engine.py &&
      poetry run python erpguard/compliance_summary.py &&
      poetry run python erpguard/reporting/generate_report.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api-db
          property: connectionString
